export enum NAV_SCREEN{
    APP_INTRO_SCREEN_ONE = 'APP_INTRO_SCREEN_ONE',
    APP_INTRO_SCREEN_TWO = 'APP_INTRO_SCREEN_TWO',
    APP_INTRO_SCREEN_THREE = 'APP_INTRO_SCREEN_THREE',
    LOGIN_SCREEN = 'LOGIN_SCREEN',
    SIGNUP_SCREEN = 'SIGNUP_SCREEN',
    HOME_SCREEN = 'HOME_SCREEN',
    PROFILE_SCREEN = 'PROFILE_SCREEN',
    SETTINGS_SCREEN = 'SETTINGS_SCREEN',
    DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
    TEXTVIEW_SCREEN = 'TEXTVIEW_SCREEN',
    MODAL_SCREEN = 'MODAL_SCREEN',
    COUNTER_USESTATE_SCREEN = 'COUNTER_USESTATE_SCREEN',
    COUNTER_CONTEXT_API_SCREEN = 'COUNTER_CONTEXT_API_SCREEN',
    COUNTER_REDUX_SCREEN = 'COUNTER_REDUX_SCREEN',
    COUNTER_REDUX_SAGA_SCREEN = 'COUNTER_REDUX_SAGA_SCREEN',
    VIEW_PAGER = 'VIEW_PAGER',
    DRAWER_HOME_SCREEN = 'DRAWER_HOME_SCREEN',
    DRAWER_FAQ_SCREEN = 'DRAWER_FAQ_SCREEN',
    DRAWER_CONTACT_US_SCREEN = 'DRAWER_CONTACT_US_SCREEN'
}

export enum FEATURE_TYPE{
    FEATURE_TEXT_VIEW = 'Text View',
    FEATURE_MODAL = 'Modal',
    FEATURE_USE_STATE_HOOK = 'Use State Hook',
    FEATURE_CONTEXT_API = 'Context API',
    FEATURE_REDUX_TOOLKIT = 'Redux Toolkit-AsyncThunk',
    FEATURE_REDUX_TOOLKIT_SAGA = 'Redux Toolkit-Saga',
    FEATURE_VIEW_PAGER = 'View Pager',
}