export enum NAV_SCREEN{
    APP_INTRO_SCREEN_ONE = 'APP_INTRO_SCREEN_ONE',
    APP_INTRO_SCREEN_TWO = 'APP_INTRO_SCREEN_TWO',
    APP_INTRO_SCREEN_THREE = 'APP_INTRO_SCREEN_THREE',
    LOGIN_SCREEN = 'LOGIN_SCREEN',
    SIGNUP_SCREEN = 'SIGNUP_SCREEN',
    HOME_SCREEN = 'HOME_SCREEN',
    PROFILE_SCREEN = 'PROFILE_SCREEN',
    SETTINGS_SCREEN = 'SETTINGS_SCREEN',
    DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
    DETAIL_SCREEN = 'DETAIL_SCREEN',
    DRAWER_HOME_SCREEN = 'DRAWER_HOME_SCREEN',
    DRAWER_FAQ_SCREEN = 'DRAWER_FAQ_SCREEN',
    DRAWER_CONTACT_US_SCREEN = 'DRAWER_CONTACT_US_SCREEN'
}